name: argo_ncp
channels:
  - conda-forge
  - pypi
  - defaults

dependencies:
  # Required for full project functionality (dont remove)
  - pytest 
  - python
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - matplotlib
  - notebook
  - pip
  - netcdf4
  - cartopy

  # For vonBerg NCP calculation
  - pandas

  # For Bieto's NEP calculations
  - glob2
  - gsw
  - seawater
  - scipy
  - cmocean
