
      SUBROUTINE alphabeta(S,T,P0,ALFNEW,BETNEW)
C *********************************************************************
C THIS PROGRAMME WRITTEN 8 JULY 1985 BY TREVOR J. McDOUGALL
C EOSALL STANDS FOR "EQUATION OF STATE ALL"
C THIS SUBROUTINE USES THE FOLLOWING FUNCTIONS WRITEN BY BOB MILLARD,
C  - THETA(S,T,P0,PR) ; SVAN(S,T,P0,SIGTHE) ; EOS8D(S,T,P0,DRV)
C THE NEW EXPANSION COEFFICIENT , ALFNEW , DUE TO HEAT , AND THE
C CORRESPONDING SALINE CONTRACTION COEFFICIENT ARE DEFINED IN
C TERMS OF THE TWO CONSERVATIVE PROPERTIES OF SEA WATER,
C NAMELY POTENTIAL TEMPERATURE (REFERED TO ANY REFERENCE LEVEL)
C AND SALINITY. THESE COEFFICIENTS ARE DEFINED IN GILL(1982)
C AND HE LABELS THEM WITH DASHES, SEE HIS SECTION 3.7.4
C
C Stripped down version of EOSALL to calculate only what is needed
C for neutral surfaces.
C
C ********************************************************************
C
      IMPLICIT DOUBLE PRECISION (A-Z)
      DOUBLE PRECISION DRV(3,8)
      EDUM=EOS8D(S,T,P0,DRV)
C ******* CALCULATE THE ORDINARY EXPANSION COEFFICIENTS, ALFOLD
C ******* BETOLD AND THE OLD COMPRESSIBILITY, GAMOLD.
      ALFOLD=-DRV(2,3)/(DRV(1,3)+1000.0)
      BETOLD=DRV(1,8)/(DRV(1,3)+1000.0)
      CALL DERTHE(S,T,P0,DTHEDT,DTHEDS,DTHEDP)
      ALFNEW=ALFOLD/DTHEDT
      BETNEW=BETOLD+ALFNEW*DTHEDS
      RETURN
      END

